# Generated by Django 3.0.7 on 2020-08-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
