# Generated by Django 3.0.7 on 2020-08-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200830_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_start_time',
            new_name='start_time',
        ),
    ]
