# Generated by Django 3.0.7 on 2020-09-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
    ]
