# Generated by Django 3.0.7 on 2020-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status_notification',
            field=models.IntegerField(default=0),
        ),
    ]
