# Generated by Django 3.0.7 on 2020-07-09 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
