# Generated by Django 3.0.7 on 2020-07-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_acceptedfriendrequests_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted_friend_notification',
            field=models.IntegerField(default=0),
        ),
    ]
