# Generated by Django 3.0.7 on 2020-08-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userprofile_accepted_friend_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='event_notification',
            field=models.IntegerField(default=0),
        ),
    ]
