# Generated by Django 3.0.7 on 2020-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
