# Generated by Django 3.0.7 on 2020-07-05 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0002_auto_20200705_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
