# Generated by Django 3.0.7 on 2020-07-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_bio'),
        ('status', '0002_status_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_user_profile', to='user.UserProfile'),
        ),
    ]
