# Generated by Django 3.0.7 on 2020-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20200705_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='liked_by_usernames',
            field=models.CharField(default='alexford', max_length=100),
            preserve_default=False,
        ),
    ]
