# Generated by Django 3.0.7 on 2020-07-05 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_status_liked_by_usernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='liked_by_usernames',
        ),
    ]
