# Generated by Django 3.0.7 on 2020-07-07 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0005_commentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_noti_liker', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_noti_status', to='status.Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_noti_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
