# Generated by Django 3.0.7 on 2020-08-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20200707_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
