# Generated by Django 3.0.7 on 2020-07-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0007_auto_20200706_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.AddField(
            model_name='status',
            name='comment',
            field=models.ManyToManyField(related_name='status_comment', to='status.Comment'),
        ),
    ]
